name: Publish RubyGem

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
